### PR TITLE
Add support for node ESModules with --experimental-modules flag

### PR DESCRIPTION
**Pull request by trxcllnt**
This PR adds support for using `text-encoding-utf-8` with node's new `--experimental-modules` flag for ESModules support:

1. rename `lib/encoding.cjs.js` to `lib/encoding.lib.js`
2. copy the `src/encoding.js` file to `lib/encoding.lib.mjs`
3. remove the extension from the "main" entry in `package.json`, `lib/encoding.lib.js` -> `lib/encoding.lib`

Points 2 and 3 are necessary because node will automatically select the "mjs" file when run with `--experimental-modules`, but only if the "main" export doesn't specify a file extension. If no "mjs" file exists, node imports the CJS form and synthesizes a default export from the `module.exports` object, leading to the following behavior:

```js
// $ node index.js
// works great
const { TextDecoder } = require('text-encoding-utf-8');
```
```js
// $ node index.mjs --experimental-modules
// throws "SyntaxError: The requested module does not provide an export named 'TextDecoder'"
import { TextDecoder } from 'text-encoding-utf-8';
```

For context: we are using this polyfill in the [Apache Arrow](https://github.com/apache/arrow) JS project (and really appreciate your efforts), and are now supporting ESModules in our library. Let me know if there's anything else I can help to get this PR merged and a new version published soon. Thanks!

### CODE REVIEW

**Review by arv — APPROVED** [review]
Nice. LGTM

**Comment by arv** [comment]
I'll have to do another push to npm later when I'm in front of my laptop.

**Comment by trxcllnt** [comment]
@arv thanks so much! I believe our next release is after thanksgiving, maybe even early next week, so no rush.

**Comment by arv** [comment]
I just pushed to npm (1.0.2).

**Pull request merged**
